//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveCodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiveCodeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actvn.arlic.
        /// </summary>
        internal static string FILE_name {
            get {
                return ResourceManager.GetString("FILE_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato del código de generación es incorrecto.
        /// </summary>
        internal static string MSG_MalFormato {
            get {
                return ResourceManager.GetString("MSG_MalFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso terminado con éxito.
        /// </summary>
        internal static string MSG_OK {
            get {
                return ResourceManager.GetString("MSG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas con la generación del fichero de activación.
        /// </summary>
        internal static string MSG_Problemas {
            get {
                return ResourceManager.GetString("MSG_Problemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los códigos no coinciden.
        /// </summary>
        internal static string MSG_TestFAIL {
            get {
                return ResourceManager.GetString("MSG_TestFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobación de códigos exitosa.
        /// </summary>
        internal static string MSG_TestOK {
            get {
                return ResourceManager.GetString("MSG_TestOK", resourceCulture);
            }
        }
    }
}
