//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerrmDiag.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HerrmDiag.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colores, Imágenes.
        /// </summary>
        internal static string AS_ResultView_Colores_Imagenes {
            get {
                return ResourceManager.GetString("AS_ResultView_Colores_Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colores, Letras.
        /// </summary>
        internal static string AS_ResultView_Colores_Letras {
            get {
                return ResourceManager.GetString("AS_ResultView_Colores_Letras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homogénea, Figuras abstractas.
        /// </summary>
        internal static string AS_ResultView_Homogenea_Figuras {
            get {
                return ResourceManager.GetString("AS_ResultView_Homogenea_Figuras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homogénea, Imágenes.
        /// </summary>
        internal static string AS_ResultView_Homogénea_Imágenes {
            get {
                return ResourceManager.GetString("AS_ResultView_Homogénea_Imágenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homogénea, Letras.
        /// </summary>
        internal static string AS_ResultView_Homognea_Letras {
            get {
                return ResourceManager.GetString("AS_ResultView_Homognea_Letras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitud de Memoria.
        /// </summary>
        internal static string ComboValue_AM {
            get {
                return ResourceManager.GetString("ComboValue_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención Sostenida Compleja (Figuras).
        /// </summary>
        internal static string ComboValue_ASC {
            get {
                return ResourceManager.GetString("ComboValue_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención Sostenida Compleja (Letras).
        /// </summary>
        internal static string ComboValue_ASC_L {
            get {
                return ResourceManager.GetString("ComboValue_ASC_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención Sostenida Simple (Figuras).
        /// </summary>
        internal static string ComboValue_ASS {
            get {
                return ResourceManager.GetString("ComboValue_ASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención Sostenida Simple.
        /// </summary>
        internal static string ComboValue_ASS_Colores {
            get {
                return ResourceManager.GetString("ComboValue_ASS_Colores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención Sostenida Simple (Letras).
        /// </summary>
        internal static string ComboValue_ASS_L {
            get {
                return ResourceManager.GetString("ComboValue_ASS_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimación del Movimiento.
        /// </summary>
        internal static string Combovalue_EM {
            get {
                return ResourceManager.GetString("Combovalue_EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoria de Figuras.
        /// </summary>
        internal static string ComboValue_MF {
            get {
                return ResourceManager.GetString("ComboValue_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pares Visuales Asociados.
        /// </summary>
        internal static string ComboValue_PVA {
            get {
                return ResourceManager.GetString("ComboValue_PVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pares Visuales Asociados (2).
        /// </summary>
        internal static string ComboValue_PVA2 {
            get {
                return ResourceManager.GetString("ComboValue_PVA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprendizaje de Palabras.
        /// </summary>
        internal static string ComboValue_RL {
            get {
                return ResourceManager.GetString("ComboValue_RL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de Reacción 2.
        /// </summary>
        internal static string ComboValue_TRC {
            get {
                return ResourceManager.GetString("ComboValue_TRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de Reacción 1.
        /// </summary>
        internal static string ComboValue_TRS {
            get {
                return ResourceManager.GetString("ComboValue_TRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actvn.arlic.
        /// </summary>
        internal static string FILE_ActKey {
            get {
                return ResourceManager.GetString("FILE_ActKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter].
        /// </summary>
        internal static string KeyName_Enter {
            get {
                return ResourceManager.GetString("KeyName_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Espacio].
        /// </summary>
        internal static string KeyName_Space {
            get {
                return ResourceManager.GetString("KeyName_Space", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso denegado.
        /// </summary>
        internal static string MSG_AccessDenied {
            get {
                return ResourceManager.GetString("MSG_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        internal static string MSG_CantFindUser {
            get {
                return ResourceManager.GetString("MSG_CantFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La categoría ha sido cambiada satisfactoriamente.
        /// </summary>
        internal static string MSG_ChangeCategoryOK {
            get {
                return ResourceManager.GetString("MSG_ChangeCategoryOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña ha sido cambiada satisfactoriamente.
        /// </summary>
        internal static string MSG_ChangePasswOK {
            get {
                return ResourceManager.GetString("MSG_ChangePasswOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compruebe que las contraseñas nuevas sean iguales.
        /// </summary>
        internal static string MSG_CheckBothPassWD {
            get {
                return ResourceManager.GetString("MSG_CheckBothPassWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cerrar la vista previa.
        /// </summary>
        internal static string MSG_ClosePreViewError {
            get {
                return ResourceManager.GetString("MSG_ClosePreViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de acceso a la base de datos.
        /// </summary>
        internal static string MSG_DB_AccessError {
            get {
                return ResourceManager.GetString("MSG_DB_AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminado.
        /// </summary>
        internal static string MSG_Done {
            get {
                return ResourceManager.GetString("MSG_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible agregar pacientes con esa edad..
        /// </summary>
        internal static string MSG_Edad_NotInRange {
            get {
                return ResourceManager.GetString("MSG_Edad_NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrando vista previa.
        /// </summary>
        internal static string MSG_Error_ClosingPreview {
            get {
                return ResourceManager.GetString("MSG_Error_ClosingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurando y ....
        /// </summary>
        internal static string MSG_Error_Configuring {
            get {
                return ResourceManager.GetString("MSG_Error_Configuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poniendo vista previa.
        /// </summary>
        internal static string MSG_Error_OpeningPreview {
            get {
                return ResourceManager.GetString("MSG_Error_OpeningPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar exportar los datos..
        /// </summary>
        internal static string MSG_Excel_ExportError {
            get {
                return ResourceManager.GetString("MSG_Excel_ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha terminado el proceso satisfactoriamente..
        /// </summary>
        internal static string MSG_Excel_ExportOK {
            get {
                return ResourceManager.GetString("MSG_Excel_ExportOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar fichero Excel base.
        /// </summary>
        internal static string MSG_Excel_FileNotFound {
            get {
                return ResourceManager.GetString("MSG_Excel_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar camino al fichero Excel base.
        /// </summary>
        internal static string MSG_Excel_PathNotFoud {
            get {
                return ResourceManager.GetString("MSG_Excel_PathNotFoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas al cargar la información de las pruebas.
        /// </summary>
        internal static string MSG_InfoNotLoaded {
            get {
                return ResourceManager.GetString("MSG_InfoNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema se ha recuperado de la pérdida de información importante. El paciente ha sido insertado con el código:.
        /// </summary>
        internal static string MSG_LostConfig {
            get {
                return ResourceManager.GetString("MSG_LostConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportando los datos a Excel....
        /// </summary>
        internal static string MSG_MainFormStatus_Exporting2Excel {
            get {
                return ResourceManager.GetString("MSG_MainFormStatus_Exporting2Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación finalizada.
        /// </summary>
        internal static string MSG_MainFormStatus_OperationComplete {
            get {
                return ResourceManager.GetString("MSG_MainFormStatus_OperationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El paciente ha sido agregado a la Base de Datos.
        /// </summary>
        internal static string MSG_Paciente_AddOK {
            get {
                return ResourceManager.GetString("MSG_Paciente_AddOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código que escogió no se encuentra disponible.
        /// </summary>
        internal static string MSG_Paciente_CodeNotAvailable {
            get {
                return ResourceManager.GetString("MSG_Paciente_CodeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro de que desea eliminar este paciente?.
        /// </summary>
        internal static string MSG_Paciente_ConfirmDelete {
            get {
                return ResourceManager.GetString("MSG_Paciente_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La actualización ha sido un éxito.
        /// </summary>
        internal static string MSG_Paciente_EditOK {
            get {
                return ResourceManager.GetString("MSG_Paciente_EditOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la entrada de los datos.
        /// </summary>
        internal static string MSG_Paciente_InputDataError {
            get {
                return ResourceManager.GetString("MSG_Paciente_InputDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, escriba una contraseña.
        /// </summary>
        internal static string MSG_PaswordMandatory {
            get {
                return ResourceManager.GetString("MSG_PaswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas al cargar la vista previa.
        /// </summary>
        internal static string MSG_PreviewNotLoaded {
            get {
                return ResourceManager.GetString("MSG_PreviewNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha concluido la búsqueda.
        /// </summary>
        internal static string MSG_SearchFinished {
            get {
                return ResourceManager.GetString("MSG_SearchFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un sujeto.
        /// </summary>
        internal static string MSG_Select_Patient {
            get {
                return ResourceManager.GetString("MSG_Select_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Test.
        /// </summary>
        internal static string MSG_Select_Test {
            get {
                return ResourceManager.GetString("MSG_Select_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testo no disponible para pacientes de {0} años.
        /// </summary>
        internal static string MSG_TestNotForSelectedAge {
            get {
                return ResourceManager.GetString("MSG_TestNotForSelectedAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ususario ha sido agregado a la Base de Datos.
        /// </summary>
        internal static string MSG_Usuario_AddOK {
            get {
                return ResourceManager.GetString("MSG_Usuario_AddOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro que desea eliminar este usuario.
        /// </summary>
        internal static string MSG_Usuario_AskForDelete {
            get {
                return ResourceManager.GetString("MSG_Usuario_AskForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no puede ser eliminado.
        /// </summary>
        internal static string MSG_Usuario_CantDelete {
            get {
                return ResourceManager.GetString("MSG_Usuario_CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario no aceptado.
        /// </summary>
        internal static string MSG_Usuario_LoginNotAcepted {
            get {
                return ResourceManager.GetString("MSG_Usuario_LoginNotAcepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario no está disponible.
        /// </summary>
        internal static string MSG_Usuario_LoginNotAvailable {
            get {
                return ResourceManager.GetString("MSG_Usuario_LoginNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un usuario.
        /// </summary>
        internal static string MSG_Usuario_SelectAnUser {
            get {
                return ResourceManager.GetString("MSG_Usuario_SelectAnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        internal static string MSG_Usuario_UserNotFoud {
            get {
                return ResourceManager.GetString("MSG_Usuario_UserNotFoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params.config.
        /// </summary>
        internal static string PATH_Config {
            get {
                return ResourceManager.GetString("PATH_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.xml.
        /// </summary>
        internal static string PATH_Xml {
            get {
                return ResourceManager.GetString("PATH_Xml", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TAS {
            get {
                object obj = ResourceManager.GetObject("TAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        internal static string TESTCODE_AM {
            get {
                return ResourceManager.GetString("TESTCODE_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASS.
        /// </summary>
        internal static string TESTCODE_ASS {
            get {
                return ResourceManager.GetString("TESTCODE_ASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EM.
        /// </summary>
        internal static string TESTCODE_EM {
            get {
                return ResourceManager.GetString("TESTCODE_EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF.
        /// </summary>
        internal static string TESTCODE_MF {
            get {
                return ResourceManager.GetString("TESTCODE_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVA.
        /// </summary>
        internal static string TESTCODE_PVA1 {
            get {
                return ResourceManager.GetString("TESTCODE_PVA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVA2.
        /// </summary>
        internal static string TESTCODE_PVA2 {
            get {
                return ResourceManager.GetString("TESTCODE_PVA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RL.
        /// </summary>
        internal static string TESTCODE_RL {
            get {
                return ResourceManager.GetString("TESTCODE_RL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRC.
        /// </summary>
        internal static string TESTCODE_TRC {
            get {
                return ResourceManager.GetString("TESTCODE_TRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRS.
        /// </summary>
        internal static string TESTCODE_TRS {
            get {
                return ResourceManager.GetString("TESTCODE_TRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Sujeto.
        /// </summary>
        internal static string TITLE_AddPatient {
            get {
                return ResourceManager.GetString("TITLE_AddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Sujeto.
        /// </summary>
        internal static string TITLE_EditPatient {
            get {
                return ResourceManager.GetString("TITLE_EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        internal static string TITLE_Results {
            get {
                return ResourceManager.GetString("TITLE_Results", resourceCulture);
            }
        }
    }
}
