//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelReportTool.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelReportTool.Res.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string ExcelColumn_AllInOne_First {
            get {
                return ResourceManager.GetString("ExcelColumn_AllInOne_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        internal static string ExcelColumn_AllInOne_Last {
            get {
                return ResourceManager.GetString("ExcelColumn_AllInOne_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        internal static string ExcelColumn_ASC_First_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_First_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI.
        /// </summary>
        internal static string ExcelColumn_ASC_First_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_First_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IW.
        /// </summary>
        internal static string ExcelColumn_ASC_First_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_First_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR.
        /// </summary>
        internal static string ExcelColumn_ASC_Last_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Last_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CX.
        /// </summary>
        internal static string ExcelColumn_ASC_Last_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Last_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KL.
        /// </summary>
        internal static string ExcelColumn_ASC_Last_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Last_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GS.
        /// </summary>
        internal static string ExcelColumn_ASC_Totals_First_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Totals_First_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CY.
        /// </summary>
        internal static string ExcelColumn_ASC_Totals_First_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Totals_First_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        internal static string ExcelColumn_ASC_Totals_First_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Totals_First_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GY.
        /// </summary>
        internal static string ExcelColumn_ASC_Totals_Last_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Totals_Last_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        internal static string ExcelColumn_ASC_Totals_Last_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Totals_Last_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KS.
        /// </summary>
        internal static string ExcelColumn_ASC_Totals_Last_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASC_Totals_Last_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF.
        /// </summary>
        internal static string ExcelColumn_ASS_First_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_First_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string ExcelColumn_ASS_First_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_First_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GZ.
        /// </summary>
        internal static string ExcelColumn_ASS_First_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_First_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU.
        /// </summary>
        internal static string ExcelColumn_ASS_Last_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Last_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA.
        /// </summary>
        internal static string ExcelColumn_ASS_Last_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Last_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO.
        /// </summary>
        internal static string ExcelColumn_ASS_Last_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Last_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EV.
        /// </summary>
        internal static string ExcelColumn_ASS_Totals_First_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Totals_First_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB.
        /// </summary>
        internal static string ExcelColumn_ASS_Totals_First_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Totals_First_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string ExcelColumn_ASS_Totals_First_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Totals_First_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB.
        /// </summary>
        internal static string ExcelColumn_ASS_Totals_Last_FIG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Totals_Last_FIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH.
        /// </summary>
        internal static string ExcelColumn_ASS_Totals_Last_IMG {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Totals_Last_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV.
        /// </summary>
        internal static string ExcelColumn_ASS_Totals_Last_LET {
            get {
                return ResourceManager.GetString("ExcelColumn_ASS_Totals_Last_LET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string ExcelColumn_PersonalData_First {
            get {
                return ResourceManager.GetString("ExcelColumn_PersonalData_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string ExcelColumn_PersonalData_Last {
            get {
                return ResourceManager.GetString("ExcelColumn_PersonalData_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Txlsdb.xlsx.
        /// </summary>
        internal static string ExcelSourceName {
            get {
                return ResourceManager.GetString("ExcelSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reporte.
        /// </summary>
        internal static string ExcelWorksheetName {
            get {
                return ResourceManager.GetString("ExcelWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe cerrar la aplicación EXCEL antes de seguir.
        /// </summary>
        internal static string MSG_CloseExcel {
            get {
                return ResourceManager.GetString("MSG_CloseExcel", resourceCulture);
            }
        }
    }
}
