//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDF_Report {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PDF_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDF_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDF_Report.PDF_Resources", typeof(PDF_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bloque{0}.
        /// </summary>
        internal static string BloqueGraphicAxisLabelFormat {
            get {
                return ResourceManager.GetString("BloqueGraphicAxisLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edad: {0}.
        /// </summary>
        internal static string DP_EdadFormat {
            get {
                return ResourceManager.GetString("DP_EdadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Aplicación: {0}.
        /// </summary>
        internal static string DP_FechaAplicacionFormat {
            get {
                return ResourceManager.GetString("DP_FechaAplicacionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nacimiento: {0}.
        /// </summary>
        internal static string DP_FechaNacimientoFormat {
            get {
                return ResourceManager.GetString("DP_FechaNacimientoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de Escolaridad: {0}.
        /// </summary>
        internal static string DP_NivelFormat {
            get {
                return ResourceManager.GetString("DP_NivelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y Apellidos: {0} {1} {2}.
        /// </summary>
        internal static string DP_NombreFormat {
            get {
                return ResourceManager.GetString("DP_NombreFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo: {0}.
        /// </summary>
        internal static string DP_SexoFormat {
            get {
                return ResourceManager.GetString("DP_SexoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aciertos.
        /// </summary>
        internal static string EP_Aciertos {
            get {
                return ResourceManager.GetString("EP_Aciertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores por Comisión.
        /// </summary>
        internal static string EP_Comisiones {
            get {
                return ResourceManager.GetString("EP_Comisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C (Criterio de la respuesta).
        /// </summary>
        internal static string EP_Criterio {
            get {
                return ResourceManager.GetString("EP_Criterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desviación Estándar de TR.
        /// </summary>
        internal static string EP_Error_TR {
            get {
                return ResourceManager.GetString("EP_Error_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice de Atención Total (IA).
        /// </summary>
        internal static string EP_IA_Total {
            get {
                return ResourceManager.GetString("EP_IA_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores por Omisión.
        /// </summary>
        internal static string EP_Omisiones {
            get {
                return ResourceManager.GetString("EP_Omisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d´ (Índice de Sensibilidad).
        /// </summary>
        internal static string EP_Sensibilidad {
            get {
                return ResourceManager.GetString("EP_Sensibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempos de Reacción (TR).
        /// </summary>
        internal static string EP_TR {
            get {
                return ResourceManager.GetString("EP_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Resultados expresadas en puntuaciones T.
        /// </summary>
        internal static string FootNote_Puntuaciones {
            get {
                return ResourceManager.GetString("FootNote_Puntuaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOQUES.
        /// </summary>
        internal static string Header_BLOQUES {
            get {
                return ResourceManager.GetString("Header_BLOQUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIDAS.
        /// </summary>
        internal static string Header_MEDIDAS {
            get {
                return ResourceManager.GetString("Header_MEDIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientación.
        /// </summary>
        internal static string Header_Orientacion {
            get {
                return ResourceManager.GetString("Header_Orientacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro.
        /// </summary>
        internal static string Header_Parametro {
            get {
                return ResourceManager.GetString("Header_Parametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string Header_Percentil {
            get {
                return ResourceManager.GetString("Header_Percentil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntaje.
        /// </summary>
        internal static string Header_Puntaje {
            get {
                return ResourceManager.GetString("Header_Puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Comisión.
        /// </summary>
        internal static string Leyend_EComision {
            get {
                return ResourceManager.GetString("Leyend_EComision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. Omisión.
        /// </summary>
        internal static string Leyend_EOmision {
            get {
                return ResourceManager.GetString("Leyend_EOmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desviación estandar tiempos de reacción.
        /// </summary>
        internal static string Leyend_ErrorTR {
            get {
                return ResourceManager.GetString("Leyend_ErrorTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indice de Atención.
        /// </summary>
        internal static string Leyend_IA {
            get {
                return ResourceManager.GetString("Leyend_IA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempos de reacción.
        /// </summary>
        internal static string Leyend_TR {
            get {
                return ResourceManager.GetString("Leyend_TR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.jpg.
        /// </summary>
        internal static string LOGO_name {
            get {
                return ResourceManager.GetString("LOGO_name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TAS {
            get {
                object obj = ResourceManager.GetObject("TAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS.jpg.
        /// </summary>
        internal static string TAS_name {
            get {
                return ResourceManager.GetString("TAS_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este reporte puede ser utilizado por el profesional como información en el contexto de un proceso de evaluación  y al igual que cualquier prueba psicológica y/o neuropsicológica no debe constituirse en la única base para un diagnóstico clínico o intervención..
        /// </summary>
        internal static string TextoPrincipal {
            get {
                return ResourceManager.GetString("TextoPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validez del protocolo.
        /// </summary>
        internal static string Title_Conclusiones {
            get {
                return ResourceManager.GetString("Title_Conclusiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Generales del Paciente:.
        /// </summary>
        internal static string Title_DatosPersonales {
            get {
                return ResourceManager.GetString("Title_DatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis Gráfico de los errores por bloque.
        /// </summary>
        internal static string Title_GraficoErrores {
            get {
                return ResourceManager.GetString("Title_GraficoErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis Gráficos de los resultados generales.
        /// </summary>
        internal static string Title_GraficosResultadosGenerales {
            get {
                return ResourceManager.GetString("Title_GraficosResultadosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análisis Gráfico de los tiempos de respuesta por bloque.
        /// </summary>
        internal static string Title_GraficoTiempos {
            get {
                return ResourceManager.GetString("Title_GraficoTiempos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados por Bloques (*).
        /// </summary>
        internal static string Title_ResultadosXBloque {
            get {
                return ResourceManager.GetString("Title_ResultadosXBloque", resourceCulture);
            }
        }
    }
}
